---
- name: Installing basic packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - python-httplib2
    - git-core

- name: ensure ntpd is at the latest version
  apt: pkg=ntp state=latest
  notify:
  - restart ntpd

- name: $azkagent_root_dir directory
  file: dest={{ azkagent_root_dir }} mode=755 owner={{ user }} group={{ group }} state=directory

- name: $azkagent_download_dir directory
  file: dest={{ azkagent_download_dir }} mode=755 owner={{ user }} group={{ group }} state=directory
