---
- name: Add docker repository key
  apt_key: url={{ docker_url }}/gpg state=present
  tags: repo

- name: Add docker repository
  copy: content='deb {{ docker_url }}/ubuntu docker main' dest={{ docker_repo_file }} owner=root group=root mode=644

- name: Add docker group
  group: name=docker state=present
  notify:
    - restart docker

- name: Add user {{ user }} in group
  user: name={{ user }} state=present append=yes groups=docker
  notify:
    - restart docker

- file: dest=/var/lib/docker state=directory owner=root group=root
  register: last_result

- name: Unpack ubuntu image
  command: tar -xf /azk/docker.tar -C /var/lib
  when: last_result.changed
  notify:
    - restart docker

- name: Install docker
  apt: pkg=lxc-docker state=latest update_cache=yes
  notify:
    - restart docker

- name: be sure docker is running and enabled
  service: name=docker state=running enabled=yes

#- name: Pull ubuntu base image
  #command: docker pull ubuntu:12.04
