---
- name: Clone etcd
  get_url: url={{ etcd_url }}
           dest={{ azkagent_download_dir }}/{{ etcd_tar }}

- name: Extract etcd
  command: chdir={{ azkagent_download_dir }}
           tar xzf {{ etcd_tar }}
           creates={{ azkagent_download_dir }}/{{ etcd_pkg }}/etcd

- name: Move etcd to /usr/bin
  file: src={{ azkagent_download_dir }}/{{ etcd_pkg }}/{{ item }} dest=/usr/bin/{{ item }} mode=755 owner=root group=root state=link force=yes
  with_items:
    - etcd
    - etcdctl
  notify:
    - restart etcd

- name: Create data directory
  file: path=/var/data/etcd
        state=directory
  notify:
    - restart etcd

- name: Copy init script for etcd server
  template: src=etcd.upstart.j2 dest=/etc/init/etcd.conf
  notify:
    - restart etcd

- name: be sure etcd is running and enabled
  service: name=etcd state=running enabled=yes

- name: Save agent ip in etcd
  uri: url=http://$etcd_host:$etcd_port/v1/keys/azk_agent_ip method=POST body="value=$azkagent_host_ip" HEADER_Content-Type="application/x-www-form-urlencoded"
