---
- hosts: vagrant
  vars:
    user: vagrant
  tasks:
    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
  roles:
    #- docker
    - etcd
